In [4]:
import pandas as pd
import numpy as np

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LinearRegression

from sklearn.metrics import accuracy_score, confusion_matrix

In [5]:
df = pd.read_csv("Dataset 2.csv")

In [6]:
df.head()

,UserID,Age,Gender,SubscriptionType,WatchHoursPerWeek,DevicesUsed,FavoriteGenre,AdClicks,MonthlySpend,SubscriptionRenewed
0,1001,22,Female,Basic,23,5,Comedy,13,353,No
1,1002,55,Male,Basic,9,4,Drama,14,317,Yes
2,1003,49,Male,Basic,8,3,Comedy,16,309,No
3,1004,39,Female,Premium,19,5,Drama,45,833,Yes
4,1005,38,Female,Premium,23,5,Sci-Fi,24,804,Yes

In [7]:
print(df.shape)

(750, 10)

In [8]:
print(df.columns)

Index(['UserID', 'Age', 'Gender', 'SubscriptionType', 'WatchHoursPerWeek',
       'DevicesUsed', 'FavoriteGenre', 'AdClicks', 'MonthlySpend',
       'SubscriptionRenewed'],
      dtype='object')

In [10]:
numerical_features = df.select_dtypes(include=['int64','float64']).columns
categorical_features = df.select_dtypes(include=['object']).columns

print("Numerical Features:")
print(numerical_features)

print("\nCategorical Features:")
print(categorical_features)

Numerical Features:
Index(['UserID', 'Age', 'WatchHoursPerWeek', 'DevicesUsed', 'AdClicks',
       'MonthlySpend'],
      dtype='object')

Categorical Features:
Index(['Gender', 'SubscriptionType', 'FavoriteGenre', 'SubscriptionRenewed'], dtype='object')

In [11]:
df.isnull().sum()

UserID                 0
Age                    0
Gender                 0
SubscriptionType       0
WatchHoursPerWeek      0
DevicesUsed            0
FavoriteGenre          0
AdClicks               0
MonthlySpend           0
SubscriptionRenewed    0
dtype: int64

In [12]:
print(df['Age'].mean())

41.824

In [13]:
print(df['WatchHoursPerWeek'].mean())

14.236

In [14]:
print(df['MonthlySpend'].mean())

689.9053333333334

In [15]:
df['SubscriptionType'].value_counts()

SubscriptionType
Basic      342
Premium    279
VIP        129
Name: count, dtype: int64

In [16]:
renewed_percentage = (df['SubscriptionRenewed']=='Yes').mean()*100

print(renewed_percentage)

46.266666666666666

In [17]:
df_encoded = df.copy()

from sklearn.preprocessing import LabelEncoder

for col in df_encoded.select_dtypes(include='object').columns:
    le = LabelEncoder()
    df_encoded[col] = le.fit_transform(df_encoded[col])

df_encoded.head()

,UserID,Age,Gender,SubscriptionType,WatchHoursPerWeek,DevicesUsed,FavoriteGenre,AdClicks,MonthlySpend,SubscriptionRenewed
0,1001,22,0,0,23,5,1,13,353,0
1,1002,55,1,0,9,4,2,14,317,1
2,1003,49,1,0,8,3,1,16,309,0
3,1004,39,0,1,19,5,2,45,833,1
4,1005,38,0,1,23,5,5,24,804,1

In [18]:
X = df_encoded.drop('SubscriptionRenewed', axis=1)

y = df_encoded['SubscriptionRenewed']

In [19]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [20]:
from sklearn.tree import DecisionTreeClassifier

dt_model = DecisionTreeClassifier(random_state=42)

dt_model.fit(X_train, y_train)

DecisionTreeClassifier(random_state=42)

In [21]:
from sklearn.metrics import accuracy_score

y_pred_dt = dt_model.predict(X_test)

dt_accuracy = accuracy_score(y_test, y_pred_dt)

print(dt_accuracy)

0.5666666666666667

In [22]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred_dt)

print(cm)

[[50 32]
 [33 35]]

In [23]:
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=5)

knn.fit(X_train, y_train)

y_pred_knn = knn.predict(X_test)

In [24]:
knn_accuracy = accuracy_score(y_test, y_pred_knn)

print("Decision Tree:", dt_accuracy)

print("KNN:", knn_accuracy)

Decision Tree: 0.5666666666666667
KNN: 0.6

In [25]:
X_reg = df_encoded.drop('MonthlySpend', axis=1)

y_reg = df_encoded['MonthlySpend']

In [26]:
X_train_reg, X_test_reg, y_train_reg, y_test_reg = train_test_split(
    X_reg,
    y_reg,
    test_size=0.2,
    random_state=42
)

In [27]:
from sklearn.linear_model import LinearRegression

lr = LinearRegression()

lr.fit(X_train_reg, y_train_reg)

LinearRegression()

In [28]:
new_user = pd.DataFrame({
    'UserID':[2000],
    'Age':[30],
    'Gender':[1],
    'SubscriptionType':[2],
    'WatchHoursPerWeek':[20],
    'DevicesUsed':[3],
    'FavoriteGenre':[1],
    'AdClicks':[10],
    'SubscriptionRenewed':[1]
})

In [29]:
prediction = lr.predict(new_user)

print(prediction)

[1331.45391956]